import type { Review } from "./types"

const IMG = (id: string) => `https://images.unsplash.com/${id}?w=800&q=80`

const IMAGES = [
  IMG("photo-1503376780353-7e6692767b70"),
  IMG("photo-1544636331-e26879cd4d9b"),
  IMG("photo-1552519507-da3b142c6e3d"),
  IMG("photo-1619767886558-efdc7b9af943"),
  IMG("photo-1536700503339-0e4f1b2d734d"),
  IMG("photo-1555215695-3004980ad54e"),
  IMG("photo-1606664515524-ed2f786a0bd6"),
  IMG("photo-1593941707882-a5bba14938c7"),
  IMG("photo-1553440569-bcc63803a83d"),
  IMG("photo-1614162692292-7ac56d7f7f1e"),
  IMG("photo-1583121274602-3e2820c69888"),
  IMG("photo-1618843479313-40f8afb4b4d1"),
]

let imgIdx = 0
const nextImg = () => {
  const url = IMAGES[imgIdx % IMAGES.length]
  imgIdx++
  return url
}

const ts = () => new Date().toISOString()

export const MOCK_REVIEWS: Review[] = [
  {
    id: "mock-byd-seal",
    slug: "byd-seal",
    title: "BYD Seal Review",
    excerpt: "A compelling EV fastback with excellent value and range. The Seal challenges established luxury sedans at a fraction of the cost.",
    featured_image: nextImg(),
    manufacturer: "BYD",
    model: "Seal",
    year: 2024,
    content: {
      pros: ["Excellent range", "Strong value proposition", "Comfortable ride", "Impressive build quality"],
      cons: ["Limited dealer network", "Infotainment quirks", "Resale value uncertainty"],
      body: "The BYD Seal represents a watershed moment for Chinese automotive exports. Built on the company's e-Platform 3.0, it delivers a driving experience that rivals the Tesla Model 3 and BMW i4 at a significantly lower price point. The Blade Battery technology ensures both safety and energy density, while the 313 hp rear-wheel-drive powertrain provides effortless acceleration."
    },
    rating: 8.6,
    status: "published",
    featured: true,
    views: 12500,
    published_at: ts(),
    created_by: "editor",
    created_at: ts(),
    updated_at: null,
    deleted_at: null,
    specs: {
      id: "spec-byd-seal", review_id: "mock-byd-seal", engine: null,
      horsepower: 320, torque: 360, transmission: "1-speed direct drive",
      drivetrain: "RWD", fuel_type: "Electric", fuel_economy: "4.2 mi/kWh",
      top_speed: "155", acceleration: "4.0", seating: 5, price: 45000,
    },
    gallery: [
      { id: "g-byd-1", review_id: "mock-byd-seal", image_url: nextImg(), alt_text: "BYD Seal - front three quarter", sort_order: 1 },
      { id: "g-byd-2", review_id: "mock-byd-seal", image_url: nextImg(), alt_text: "BYD Seal - rear profile", sort_order: 2 },
    ],
  },
  {
    id: "mock-nio-et7",
    slug: "nio-et7",
    title: "NIO ET7 Review",
    excerpt: "A tech-forward luxury EV that redefines the executive sedan segment with autonomous driving capabilities.",
    featured_image: nextImg(),
    manufacturer: "NIO",
    model: "ET7",
    year: 2024,
    content: {
      pros: ["Cutting-edge autonomous tech", "Luxurious interior", "Dual-motor AWD performance", "Battery swap capability"],
      cons: ["Premium pricing", "Limited service centers", "Heavy curb weight"],
      body: "The NIO ET7 is the Chinese automaker's flagship sedan, designed to take on the Mercedes EQS and BMW i7. With NIO's latest NAD (NIO Autonomous Driving) suite featuring 33 sensors and 4 NVIDIA Orin chips, it promises level 4 autonomy readiness. The 480 kW dual-motor setup delivers exhilarating performance while the 150 kWh semi-solid state battery option enables over 1,000 km of range."
    },
    rating: 8.2,
    status: "published",
    featured: true,
    views: 8200,
    published_at: ts(),
    created_by: "editor",
    created_at: ts(),
    updated_at: null,
    deleted_at: null,
    specs: {
      id: "spec-nio-et7", review_id: "mock-nio-et7", engine: null,
      horsepower: 644, torque: 627, transmission: "1-speed direct drive",
      drivetrain: "AWD", fuel_type: "Electric", fuel_economy: "3.8 mi/kWh",
      top_speed: "155", acceleration: "3.9", seating: 5, price: 70000,
    },
    gallery: [
      { id: "g-nio-1", review_id: "mock-nio-et7", image_url: nextImg(), alt_text: "NIO ET7 - front view", sort_order: 1 },
    ],
  },
  {
    id: "mock-xpeng-p7",
    slug: "xpeng-p7",
    title: "XPeng P7 Review",
    excerpt: "A value-packed EV sedan with sporty handling and one of the best driver assistance systems in its class.",
    featured_image: nextImg(),
    manufacturer: "XPeng",
    model: "P7",
    year: 2024,
    content: {
      pros: ["Sharp handling dynamics", "Competitive pricing", "Advanced driver assistance", "Sleek coupe-like design"],
      cons: ["Rear seat space is tight", "Interior material quality", "Brand recognition"],
      body: "The XPeng P7 has been a revelation in the EV sports sedan segment. Its low center of gravity, thanks to the skateboard battery pack, combined with a sophisticated multi-link suspension, delivers cornering capabilities that embarrass far more expensive European rivals. The XPILOT 3.0 system offers highway autonomous driving that rivals Tesla's Autopilot."
    },
    rating: 7.8,
    status: "published",
    featured: false,
    views: 5400,
    published_at: ts(),
    created_by: "editor",
    created_at: ts(),
    updated_at: null,
    deleted_at: null,
    specs: {
      id: "spec-xp-p7", review_id: "mock-xpeng-p7", engine: null,
      horsepower: 430, torque: 390, transmission: "1-speed direct drive",
      drivetrain: "RWD", fuel_type: "Electric", fuel_economy: "4.0 mi/kWh",
      top_speed: "140", acceleration: "4.5", seating: 5, price: 40000,
    },
    gallery: [
      { id: "g-xp-1", review_id: "mock-xpeng-p7", image_url: nextImg(), alt_text: "XPeng P7 - three quarter", sort_order: 1 },
    ],
  },
  {
    id: "mock-byd-dolphin",
    slug: "byd-dolphin",
    title: "BYD Dolphin Review",
    excerpt: "A compact EV hatchback that delivers big value, impressive range, and surprising interior space for its footprint.",
    featured_image: nextImg(),
    manufacturer: "BYD",
    model: "Dolphin",
    year: 2024,
    content: {
      pros: ["Exceptional value for money", "Spacious interior for its size", "Low running costs", "Agile city driving"],
      cons: ["Modest highway range", "Basic infotainment", "Firm ride on rough roads"],
      body: "The BYD Dolphin is redefining what buyers can expect from an entry-level EV. Based on the e-Platform 3.0, it offers up to 427 km of range (NEDC) from its Blade Battery pack. The rotating 12.8-inch infotainment screen is a party trick borrowed from its larger siblings, and the interior packaging is remarkably clever for a car that's barely 4.1 meters long."
    },
    rating: 8.0,
    status: "published",
    featured: true,
    views: 9800,
    published_at: ts(),
    created_by: "editor",
    created_at: ts(),
    updated_at: null,
    deleted_at: null,
    specs: {
      id: "spec-dolphin", review_id: "mock-byd-dolphin", engine: null,
      horsepower: 201, torque: 229, transmission: "1-speed direct drive",
      drivetrain: "FWD", fuel_type: "Electric", fuel_economy: "4.5 mi/kWh",
      top_speed: "100", acceleration: "7.0", seating: 5, price: 28000,
    },
    gallery: [
      { id: "g-dol-1", review_id: "mock-byd-dolphin", image_url: nextImg(), alt_text: "BYD Dolphin - front", sort_order: 1 },
    ],
  },
  {
    id: "mock-byd-han",
    slug: "byd-han-ev",
    title: "BYD Han EV Review",
    excerpt: "A full-size executive sedan that proves China can build a genuine Mercedes S-Class rival at half the price.",
    featured_image: nextImg(),
    manufacturer: "BYD",
    model: "Han EV",
    year: 2024,
    content: {
      pros: ["Stunning design", "Luxurious rear seat experience", "Blade Battery safety", "Silent cabin"],
      cons: ["Thirsty at high speeds", "Overly assisted steering", "No frunk space"],
      body: "The BYD Han EV is the car that announced China's arrival in the luxury segment. Its dramatic fastback silhouette, combined with a cabin that pampers rear passengers with heated, ventilated, and massaging seats, makes it a compelling alternative to the Mercedes E-Class. The 85.4 kWh Blade Battery pack provides up to 521 km of range."
    },
    rating: 8.4,
    status: "published",
    featured: true,
    views: 11200,
    published_at: ts(),
    created_by: "editor",
    created_at: ts(),
    updated_at: null,
    deleted_at: null,
    specs: {
      id: "spec-han", review_id: "mock-byd-han", engine: null,
      horsepower: 517, torque: 516, transmission: "1-speed direct drive",
      drivetrain: "AWD", fuel_type: "Electric", fuel_economy: "3.6 mi/kWh",
      top_speed: "115", acceleration: "3.9", seating: 5, price: 52000,
    },
    gallery: [
      { id: "g-han-1", review_id: "mock-byd-han", image_url: nextImg(), alt_text: "BYD Han EV - front three quarter", sort_order: 1 },
    ],
  },
  {
    id: "mock-nio-es8",
    slug: "nio-es8",
    title: "NIO ES8 Review",
    excerpt: "A premium three-row electric SUV with benchmark interior quality and NIO's innovative battery swap ecosystem.",
    featured_image: nextImg(),
    manufacturer: "NIO",
    model: "ES8",
    year: 2024,
    content: {
      pros: ["Sumptuous interior", "Third-row practicality", "Battery swap technology", "Powerful dual motors"],
      cons: ["Expensive", "Limited cargo space with all seats up", "Complex infotainment"],
      body: "The NIO ES8 is the vehicle that established NIO as a credible luxury automaker. Now in its second generation, the ES8 offers a beautifully crafted interior with premium Nappa leather, microsuede headlining, and powered everything. The 480 kW dual-motor powertrain delivers effortless performance."
    },
    rating: 7.9,
    status: "published",
    featured: false,
    views: 7200,
    published_at: ts(),
    created_by: "editor",
    created_at: ts(),
    updated_at: null,
    deleted_at: null,
    specs: {
      id: "spec-es8", review_id: "mock-nio-es8", engine: null,
      horsepower: 644, torque: 620, transmission: "1-speed direct drive",
      drivetrain: "AWD", fuel_type: "Electric", fuel_economy: "3.2 mi/kWh",
      top_speed: "124", acceleration: "4.1", seating: 7, price: 78000,
    },
    gallery: [
      { id: "g-es8-1", review_id: "mock-nio-es8", image_url: nextImg(), alt_text: "NIO ES8 - front", sort_order: 1 },
    ],
  },
  {
    id: "mock-li-l9",
    slug: "li-auto-l9",
    title: "Li Auto L9 Review",
    excerpt: "A revolutionary EREV full-size SUV that combines electric daily driving with ICE range-extended peace of mind.",
    featured_image: nextImg(),
    manufacturer: "Li Auto",
    model: "L9",
    year: 2024,
    content: {
      pros: ["Clever EREV range extender", "Genuine 6-seat family hauler", "Gaming-capable infotainment", "Air suspension standard"],
      cons: ["Thirsty when range extender active", "Not as refined as pure EVs", "Heavy vehicle"],
      body: "The Li Auto L9 has become one of China's most popular premium SUVs by solving the range anxiety problem with an ingenious approach: a large 44.5 kWh battery pack for 215 km of electric-only range, coupled with a 1.5L turbo range extender that provides unlimited range on long trips. The interior features a massive dual 15.7-inch OLED screens."
    },
    rating: 8.1,
    status: "published",
    featured: true,
    views: 10100,
    published_at: ts(),
    created_by: "editor",
    created_at: ts(),
    updated_at: null,
    deleted_at: null,
    specs: {
      id: "spec-l9", review_id: "mock-li-l9", engine: "1.5L Turbo Range Extender",
      horsepower: 449, torque: 457, transmission: "1-speed direct drive",
      drivetrain: "AWD", fuel_type: "EREV", fuel_economy: "3.8 mi/kWh (combined)",
      top_speed: "112", acceleration: "5.3", seating: 6, price: 65000,
    },
    gallery: [
      { id: "g-l9-1", review_id: "mock-li-l9", image_url: nextImg(), alt_text: "Li Auto L9 - front", sort_order: 1 },
    ],
  },
  {
    id: "mock-xpeng-g9",
    slug: "xpeng-g9",
    title: "XPeng G9 Review",
    excerpt: "A technology tour de force SUV with 800V architecture, ultra-fast charging, and industry-leading parking assistance.",
    featured_image: nextImg(),
    manufacturer: "XPeng",
    model: "G9",
    year: 2024,
    content: {
      pros: ["800V ultra-fast charging", "Excellent driver assistance", "Spacious interior", "Refined ride quality"],
      cons: ["Steep price for range", "Software still maturing", "Limited brand trust in export markets"],
      body: "The XPeng G9 represents the pinnacle of XPeng's engineering. Its 800V architecture enables charging from 10% to 80% in just 15 minutes at compatible 480 kW chargers. The XNGP system provides near full autonomous driving on Chinese highways, and the 5D multi-sensory immersive experience syncs ambient lighting, audio, seat massage, and climate."
    },
    rating: 8.3,
    status: "published",
    featured: true,
    views: 8700,
    published_at: ts(),
    created_by: "editor",
    created_at: ts(),
    updated_at: null,
    deleted_at: null,
    specs: {
      id: "spec-g9", review_id: "mock-xpeng-g9", engine: null,
      horsepower: 536, torque: 531, transmission: "1-speed direct drive",
      drivetrain: "AWD", fuel_type: "Electric", fuel_economy: "3.5 mi/kWh",
      top_speed: "124", acceleration: "3.9", seating: 5, price: 68000,
    },
    gallery: [
      { id: "g-g9-1", review_id: "mock-xpeng-g9", image_url: nextImg(), alt_text: "XPeng G9 - three quarter", sort_order: 1 },
    ],
  },
  {
    id: "mock-tesla-m3",
    slug: "tesla-model-3-performance",
    title: "Tesla Model 3 Performance Review",
    excerpt: "The benchmark electric sports sedan gets sharper, faster, and more refined with the 2024 Highland update.",
    featured_image: nextImg(),
    manufacturer: "Tesla",
    model: "Model 3 Performance",
    year: 2024,
    content: {
      pros: ["Blistering acceleration", "Supercharger network access", "Mature software ecosystem", "Improved Highland refinement"],
      cons: ["Build quality inconsistency", "No Apple CarPlay", "Minimalist interior not for everyone"],
      body: "The Tesla Model 3 Performance remains the benchmark that all electric sports sedans are measured against. The Highland refresh brings improved sound insulation, a revised suspension for better comfort, and ventilated front seats. The Track Mode V3 allows unprecedented control over torque vectoring and stability systems."
    },
    rating: 8.8,
    status: "published",
    featured: true,
    views: 22000,
    published_at: ts(),
    created_by: "editor",
    created_at: ts(),
    updated_at: null,
    deleted_at: null,
    specs: {
      id: "spec-tesla-m3", review_id: "mock-tesla-m3", engine: null,
      horsepower: 510, torque: 545, transmission: "1-speed direct drive",
      drivetrain: "AWD", fuel_type: "Electric", fuel_economy: "4.3 mi/kWh",
      top_speed: "162", acceleration: "3.1", seating: 5, price: 55000,
    },
    gallery: [
      { id: "g-tes-1", review_id: "mock-tesla-m3", image_url: nextImg(), alt_text: "Tesla Model 3 Performance - front", sort_order: 1 },
    ],
  },
  {
    id: "mock-porsche-taycan",
    slug: "porsche-taycan-turbo",
    title: "Porsche Taycan Turbo Review",
    excerpt: "The definitive electric sports car that drives like a Porsche should, with soul-stirring performance and real track capability.",
    featured_image: nextImg(),
    manufacturer: "Porsche",
    model: "Taycan Turbo",
    year: 2024,
    content: {
      pros: ["Class-leading driving dynamics", "800V charging architecture", "Premium interior quality", "Real track endurance"],
      cons: ["Limited range vs rivals", "Expensive options", "Tight rear seat space"],
      body: "The Porsche Taycan Turbo proves that electrification and driver engagement are not mutually exclusive. With a two-speed transmission on the rear axle for both launch performance and high-speed efficiency, and adaptive air suspension that defies physics, it remains the ultimate driver's EV. The 93.4 kWh Performance Battery Plus delivers sustained power."
    },
    rating: 9.0,
    status: "published",
    featured: true,
    views: 18500,
    published_at: ts(),
    created_by: "editor",
    created_at: ts(),
    updated_at: null,
    deleted_at: null,
    specs: {
      id: "spec-taycan", review_id: "mock-porsche-taycan", engine: null,
      horsepower: 616, torque: 626, transmission: "2-speed automatic",
      drivetrain: "AWD", fuel_type: "Electric", fuel_economy: "3.0 mi/kWh",
      top_speed: "161", acceleration: "3.0", seating: 4, price: 155000,
    },
    gallery: [
      { id: "g-tay-1", review_id: "mock-porsche-taycan", image_url: nextImg(), alt_text: "Porsche Taycan Turbo - front", sort_order: 1 },
      { id: "g-tay-2", review_id: "mock-porsche-taycan", image_url: nextImg(), alt_text: "Porsche Taycan Turbo - rear", sort_order: 2 },
    ],
  },
  {
    id: "mock-bmw-i7",
    slug: "bmw-i7-m70",
    title: "BMW i7 M70 Review",
    excerpt: "The ultimate electric luxury sedan with M performance DNA and a sumptuous theater-grade rear cabin experience.",
    featured_image: nextImg(),
    manufacturer: "BMW",
    model: "i7 M70",
    year: 2024,
    content: {
      pros: ["Brutal M performance", "Executive rear lounge", "31-inch theater screen", "Impressive build quality"],
      cons: ["Contentious styling", "Heavy weight", "Very expensive"],
      body: "The BMW i7 M70 is the most powerful electric BMW ever built. With 660 hp and a 101.7 kWh battery, it combines waft-ability with supercar acceleration. The optional 31-inch 8K rear theater screen with Amazon Fire TV integration transforms the back seat into a private cinema, while the Executive Lounge package includes a reclining passenger seat."
    },
    rating: 8.7,
    status: "published",
    featured: false,
    views: 14500,
    published_at: ts(),
    created_by: "editor",
    created_at: ts(),
    updated_at: null,
    deleted_at: null,
    specs: {
      id: "spec-i7", review_id: "mock-bmw-i7", engine: null,
      horsepower: 660, torque: 700, transmission: "1-speed direct drive",
      drivetrain: "AWD", fuel_type: "Electric", fuel_economy: "2.8 mi/kWh",
      top_speed: "155", acceleration: "3.5", seating: 5, price: 170000,
    },
    gallery: [
      { id: "g-i7-1", review_id: "mock-bmw-i7", image_url: nextImg(), alt_text: "BMW i7 M70 - front", sort_order: 1 },
    ],
  },
  {
    id: "mock-mb-eqs",
    slug: "mercedes-eqs-53",
    title: "Mercedes-AMG EQS 53 Review",
    excerpt: "The pinnacle of electric luxury meets AMG performance in a silently devastating executive express.",
    featured_image: nextImg(),
    manufacturer: "Mercedes-Benz",
    model: "AMG EQS 53",
    year: 2024,
    content: {
      pros: ["Effortless AMG performance", "Hyperscreen dashboard is spectacular", "Plush ride comfort", "Excellent build quality"],
      cons: ["Massive curb weight", "Hyperscreen is a fingerprint magnet", "Very expensive entry price"],
      body: "The Mercedes-AMG EQS 53 combines the technological tour de force of the EQS luxury sedan with AMG's performance tuning expertise. The result is a 649 hp electric executive that can waft silently or deliver spine-compressing acceleration on demand. The 107.8 kWh battery provides genuine long-distance capability."
    },
    rating: 8.5,
    status: "published",
    featured: false,
    views: 13200,
    published_at: ts(),
    created_by: "editor",
    created_at: ts(),
    updated_at: null,
    deleted_at: null,
    specs: {
      id: "spec-eqs", review_id: "mock-mb-eqs", engine: null,
      horsepower: 649, torque: 700, transmission: "1-speed direct drive",
      drivetrain: "AWD", fuel_type: "Electric", fuel_economy: "2.9 mi/kWh",
      top_speed: "155", acceleration: "3.4", seating: 5, price: 160000,
    },
    gallery: [
      { id: "g-eqs-1", review_id: "mock-mb-eqs", image_url: nextImg(), alt_text: "Mercedes-AMG EQS 53 - front", sort_order: 1 },
    ],
  },
]
